# Generated by Django 3.2.18 on 2024-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='market_prod_created_01dfb7_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='market_prod_created_a24064_idx'),
        ),
    ]
